<a href="https://colab.research.google.com/github/r2x4/ETL_alura_oracle/blob/main/colab_datos_sql.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Datos SQL o bases de datos**

### **crear un banco de Datos**

In [5]:
# importar biblioteca

import sqlalchemy

In [6]:
from sqlalchemy import create_engine, MetaData, Table, inspect, text, Column, Integer, String

# crear el banco de datos

In [9]:
# crear el motor de datos

engine = create_engine('sqlite:///:memory:')

In [10]:
from google.colab import files
uploaded = files.upload()

Saving clientes_banco.csv to clientes_banco.csv

In [15]:
# Importar datos clientes Banco

import pandas as pd

datos_clientes = 'clientes_banco.csv'

In [19]:
# generar la variable para el banco

archivo = 'clientes_banco.csv'

In [20]:
# generar variable y leer la avriable del banco

datos = pd.read_csv(archivo)

In [21]:
datos.head()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio

In [22]:
datos.tail()

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
438458,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438459,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438460,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438461,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438462,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [24]:
datos.sample(5)

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
356901,6481167,39,Nivel superior,Relación-estable,2,Business Partner,Gerencia,9,436500.0,1,Casa/Departamento propio
428555,7077676,29,Nivel intermedio,Casado,3,Empleado,Chofer,2,202500.0,1,Vive con los padres
424916,7197081,52,Nivel intermedio,Casado,2,Empleado estatal,Cocina,2,157500.0,0,Casa/Departamento propio
230646,5994130,38,Nivel superior,Divorciado,1,Business Partner,Otro,3,180000.0,0,Casa/Departamento propio
127236,6643547,52,Nivel intermedio,Casado,2,Empleado,Construcción Civil,32,135000.0,0,Casa/Departamento propio

In [25]:
type(datos)

pandas.core.frame.DataFrame

In [26]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438463 entries, 0 to 438462
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   ID_Cliente          438463 non-null  int64
 1   Edad                438463 non-null  int64
 2   Grado_estudio       438463 non-null  object
 3   Estado_civil        438463 non-null  object
 4   Tamaño_familia      438463 non-null  int64
 5   Categoria_de_renta  438463 non-null  object
 6   Ocupacion           438463 non-null  object
 7   Años_empleado       438463 non-null  int64
 8   Rendimiento_anual   438463 non-null  float64
 9   Tiene_carro         438463 non-null  int64
 10  Vivienda            438463 non-null  object
dtypes: float64(1), int64(5), object(5)
memory usage: 36.8+ MB

In [27]:
datos.shape

(438463, 11)

# llevarlo a sql

In [28]:
# crear tabla

datos.to_sql('clientes', engine, index=False)

438463

In [31]:
# inspeccionar el sql

inspector = inspect(engine)

In [32]:
print(inspector.get_table_names())

['clientes']

In [34]:
# Hacemos la Query

query = 'SELECT * FROM clientes WHERE categoria_de_renta = "Empleado"'

In [39]:
empleado = pd.read_sql(sql=text(query), con = engine.connect())

In [38]:
empleado

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

# **Se guarda en una tabla SQL**

In [40]:
# exportar a SQL

empleado.to_sql('empleado', con = engine.connect(), index=False)

226059

In [44]:
# ver la tablas de sql

pd.read_sql(sql=text('SELECT * FROM empleado'), con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [50]:
# ver unas columnas de la  tabla de sql se llaman las columnas por texto o num.

pd.read_sql_table('empleado', con = engine.connect(), columns=[0,1,2,5,7])

        ID_Cliente  Edad     Grado_estudio Categoria_de_renta  Años_empleado
0          5008804    32    Nivel superior           Empleado             12
1          5008805    32    Nivel superior           Empleado             12
2          5008806    58  Nivel intermedio           Empleado              3
3          5008815    46    Nivel superior           Empleado              2
4          5112956    46    Nivel superior           Empleado              2
...            ...   ...               ...                ...            ...
226054     6837905    43  Nivel intermedio           Empleado              7
226055     6837906    43  Nivel intermedio           Empleado              7
226056     6839936    34  Nivel intermedio           Empleado              5
226057     6840222    43  Nivel intermedio           Empleado              8
226058     6842885    51  Nivel intermedio           Empleado              3

[226059 rows x 5 columns]

# **Actualizando banco de datos**

In [ ]:
# query

query = 'SELECT * FROM clientes'

In [51]:
# llamar base de datos y borra un cliente

pd.read_sql(sql=text(query), con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008804,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
2,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
3,5008815,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
4,5112956,46,Nivel superior,Casado,2,Empleado,Contabilidad,2,270000.0,1,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
226054,6837905,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226055,6837906,43,Nivel intermedio,Casado,3,Empleado,Otro,7,355050.0,1,Casa/Departamento propio
226056,6839936,34,Nivel intermedio,Casado,3,Empleado,Construcción Civil,5,135000.0,1,Casa/Departamento propio
226057,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
226058,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [53]:
# borrar el registro se fue el cliente

from sqlalchemy.exc import SQLAlchemyError

query = 'DELETE FROM clientes WHERE ID_Cliente = 5008804'
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print("Registro borrados: ", r_set.rowcount)

Registro borrados:  1

In [55]:
# volver la leer la tabla sql

pd.read_sql_table('clientes', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

# **Actualizar datos de un Cliente**

In [57]:
# Actualizar datos de un cliente

query = "UPDATE clientes SET Grado_estudio='Nivel superior' WHERE ID_Cliente = 5008808"
try:
    r_set = engine.connect().execute(text(query))
except SQLAlchemyError as e:
    print(e)
else:
    print("Registro actualizados: ", r_set.rowcount)

Registro actualizados:  1

In [58]:
# volver la leer la tabla sql

pd.read_sql_table('clientes', con = engine.connect())

,ID_Cliente,Edad,Grado_estudio,Estado_civil,Tamaño_familia,Categoria_de_renta,Ocupacion,Años_empleado,Rendimiento_anual,Tiene_carro,Vivienda
0,5008805,32,Nivel superior,Relación-estable,2,Empleado,Otro,12,427500.0,1,Departamento alquilado
1,5008806,58,Nivel intermedio,Casado,2,Empleado,Seguridad,3,112500.0,1,Casa/Departamento propio
2,5008808,52,Nivel superior,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
3,5008809,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
4,5008810,52,Nivel intermedio,Soltero,1,Business Partner,Ventas,8,270000.0,0,Casa/Departamento propio
...,...,...,...,...,...,...,...,...,...,...,...
438457,6840104,62,Nivel intermedio,Divorciado,1,Pensionista,Otro,0,135000.0,0,Casa/Departamento propio
438458,6840222,43,Nivel intermedio,Soltero,1,Empleado,Construcción Civil,8,103500.0,0,Casa/Departamento propio
438459,6841878,22,Nivel superior,Soltero,1,Business Partner,Ventas,1,54000.0,0,Vive con los padres
438460,6842765,59,Nivel intermedio,Casado,2,Pensionista,Otro,0,72000.0,0,Casa/Departamento propio
438461,6842885,51,Nivel intermedio,Casado,2,Empleado,Ventas,3,121500.0,0,Casa/Departamento propio

In [59]:
# inspeccionar el sql

inspector = inspect(engine)

In [60]:
print(inspector.get_table_names())

['clientes', 'empleado']